version: '3.8'
services:
  onikani:
    build: .
    volumes:
      - ./:/app
    working_dir: /app
    tty: true
    depends_on:
      - db
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: onikani
      POSTGRES_USER: onikani
      POSTGRES_PASSWORD: onikani_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
